# This file describes a Fastly Compute@Edge package. To learn more visit:
# https://developer.fastly.com/reference/fastly-toml/

authors = ["tristanlee85@gmail.com"]
description = "A basic starter kit that demonstrates routing, simple synthetic responses and overriding caching rules."
language = "javascript"
manifest_version = 2
name = "fastly-edge-compute"
service_id = "4whDGCI0Tvkl9al4T8vUWg"
